In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("churn.db")

In [3]:
query = "SELECT COUNT(*) AS total_customers FROM customers"

pd.read_sql(query, conn)

   total_customers
0             7043

In [4]:
query = """
SELECT churn, COUNT(*) AS customers
FROM customers
GROUP BY churn
"""

pd.read_sql(query, conn)

  Churn  customers
0    No       5174
1   Yes       1869

In [6]:
query = """
SELECT Contract, AVG(MonthlyCharges) AS avg_monthly_charge
FROM customers
GROUP BY Contract
"""

pd.read_sql(query, conn)

         Contract  avg_monthly_charge
0  Month-to-month           66.398490
1        One year           65.048608
2        Two year           60.770413

In [9]:
import pandas as pd

df = pd.read_csv("customer.csv")

df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [11]:
import pandas as pd
import sqlite3

df = pd.read_csv("customer.csv")
conn = sqlite3.connect("churn.db")

In [12]:
import os
print(os.listdir())

['churn.db', 'Customer.csv']

In [13]:
os.listdir()

['churn.db', 'Customer.csv']

In [14]:
import pandas as pd

df = pd.read_csv("Customer.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [15]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [16]:
import sqlite3

conn = sqlite3.connect("churn.db")

df.to_sql("customers", conn, if_exists="replace", index=False)

print("Imported successfully")

Imported successfully

In [17]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("churn.db")

In [18]:
query = "SELECT COUNT(*) AS total_customers FROM customers"

pd.read_sql(query, conn)

   total_customers
0             7043

In [20]:
query = """
SELECT Churn, COUNT(*) AS customers
FROM customers
GROUP BY Churn
"""

pd.read_sql(query, conn)

  Churn  customers
0    No       5174
1   Yes       1869

In [21]:
query = """
SELECT Contract, COUNT(*) AS customers
FROM customers
GROUP BY Contract
"""

pd.read_sql(query, conn)

         Contract  customers
0  Month-to-month       3875
1        One year       1473
2        Two year       1695

In [22]:
query = """
SELECT Contract, AVG(MonthlyCharges) AS avg_monthly_charge
FROM customers
GROUP BY Contract
"""

pd.read_sql(query, conn)

         Contract  avg_monthly_charge
0  Month-to-month           66.398490
1        One year           65.048608
2        Two year           60.770413

In [23]:
query = """
SELECT PaymentMethod, COUNT(*) AS customers
FROM customers
GROUP BY PaymentMethod
ORDER BY customers DESC
"""

pd.read_sql(query, conn)

               PaymentMethod  customers
0           Electronic check       2365
1               Mailed check       1612
2  Bank transfer (automatic)       1544
3    Credit card (automatic)       1522